<?php
/*******************************************************
*
*     CLASS SELECTION AND REGISTRATION SYSTEM
*       from PHP and MySQL, A Beginner's Guide
*     by Marty Matthews, published 2014 McGraw-Hill
*
*   sendemail.php A new registration record is written
*   to disk and a confirmation email is sent to the
*  student. Called by confirm.php and calls classes.php
*
********************************************************
*CAUTION, USE AT YOUR OWN RISK, NO WARRANTY OF ANY KIND
********************************************************/

//Connect to the ClassRegistration database
	$connection = mysqli_connect("localhost", "root", "", "classregistration");
	if (!$connection) {
		echo "Cannot connect to MySQL. ", mysqli_connect_error($connection);
		exit();
	}
//Get Class ID from confirm.php
	$classid = ($_GET['classid']);

//Get email address from confirm.php
	$email = ($_GET['email']);

//Add record to the registration table
 	$query = "INSERT INTO registration(class_id, student_email)
			VALUES('$classid', '$email')";
	$result = mysqli_query($connection, $query);
	if (!$result) {
		echo "Insert to registration failed. ", mysqli_error($connection);
		exit();
	}
//Get the registration ID generated by insert.
	$regid = mysqli_insert_id($connection);

///Get record from the class table
 	$query = "SELECT * From class WHERE class_id = $classid";
	$result = mysqli_query($connection, $query);
	if (!$result) {
		echo "Select from class failed. ", mysqli_error($connection);
		exit();
	}
//Get selected class (row) from class table
	$classrow = mysqli_fetch_assoc($result);

//Get record from the student table
 	$query = "SELECT * From student WHERE student_email = '$email'";
	$result1 = mysqli_query($connection, $query);
	if (!result1) {
		echo "Select from student failed. ", mysqli_error($connection);
		exit();
	}
//Get selected student (row) from student table
	$sturow = mysqli_fetch_assoc($result1);

//Get record from the registration table
	$query3 = "SELECT * FROM registration WHERE reg_id = '$regid'";
	$result3 = mysql_query($connection, $query3);
	if (!result3) {
		echo "Select from registration failed. ", mysqli_error($connection);
		exit();
	}
//Get registration (row) from registration table
	$regrow = mysqli_fetch_assoc($result3);

//Confirmation Email
$to_client = $sturow['student_name']. ' <'.$sturow['student_email'].'>';
$sub_client = 'Class Registration';
$msg_client = 'Thank you for your class registration. Here is the necessary information:'."\n\n";
$msg_client .= 'Registration number: '.$regrow['reg_id']."\n";
$msg_client .= 'Class ID: '. $classid . "\n";
$msg_client .= 'Class Title: '.$sturow['class_title']."\n";
$msg_client .= 'Class Start Date: '.$sturow['class_start']."\n";
$msg_client .= 'Class Cost: '. "$" . $sturow['class_cost']."\n";
$msg_client .= 'Registration date: '.$regrow['reg_date']."\n";
$msg_client .= "\n\n";
$msg_client .= 'Your Email Address: '.$sturow['email_address']."\n";
$msg_client .= 'Your Name: '.$sturow['student_name']. "\n";
$msg_client .= 'Your Phone: '.$sturow['student_phone']."\n\n";
$msg_client .= 'Please contact us to arrange payment at:'."\n";
$msg_client .= 'info@matthewstechnology.com'."\n";
$msg_client .= "\n\n";
$msg_client .= 'Thanks again,'."\n\n";
$msg_client .= 'Matthews Technology'."\n\n";
$addl_headers_client = 'From: Matthews Technology <info@matthewstechnology.com>'."\n\n";

mail($to_client,$sub_client,$msg_client,$addl_headers_client);

?>

<!DOCTYPE html>
<html>
    <head>
   		<meta charset="utf-8">
		<title>Class Registration Completed</title>
		<link rel= "stylesheet" type= "text/css" href= "../ClassRegistration/registration.css"/>
		<script language="JavaScript" type= "text/javascript"></script>
	</head>
	<!-- Put cursor in the first field -->
	<body onLoad="document.form1.complete.focus();">
		<div id="wrapper">
			<div id="header">
				<img src="../ClassRegistration/MatTechLogo.gif" alt="Matthews Technology" />
				<h1 id="title">Class Selection and Registration</h1>

			</div> <!-- id="header" -->
			<div id="hnav">
				<table width="400" border="0" cellspacing="2" cellpadding="2">
  				  <tr>
			        <td><a href="../ClassRegistration/index.php">Home</a> </td>
			        <td><a href="../ClassRegistration/index.php">About</a> </td>
			        <td><a href="../ClassRegistration/index.php">Support</a> </td>
			        <td><a href="../ClassRegistration/AdministratorAuthentication/adminAuthen.php">Maintain</a> </td>
  		    	  </tr>
				</table>

			</div> <!-- id="hnav" -->
			<div id="vnav">
				<table width="120" border="0" cellspacing="2" cellpadding="2">
    				<tr>
				        <td id="vhead">Go To: </td>
				    </tr>
					<tr>
				        <td><a href="classes.php">Class List</a> </td>
				    </tr>
				    <tr>
				        <td><a href="emailentry.php?recordID=<?php echo $classrow ['class_id']; ?>">Email Entry</a>
				        </td>
				    </tr>
				</table>

			</div> <!-- id="vnav" -->
			<div id="main">
				<h1 id="maintitle">Class Database Update</h1>
				<p id="mainpara">Thank you for completing class regristration!<br />
					 Please click Complete.</p>

				<div id="form">
						<!-- Go to classes.php after clicking Complete -->
						<form action="classes.php" method="post" name="form1">
						 	<input type="submit" name="submit" value="Complete" />
						</form>
				</div> <!-- id=form -->

				<!-- Begin from template -->

				<p class="red">&nbsp</p>

			</div> <!-- id="main" -->
			<div id="footer">
				<p id="copyright">
					Copyright &copy:2008 -
					<?php
						 date_default_timezone_set('America/Vancouver');
						 echo date('Y');
					?>
					Matthews Technology
				</p>
				<p id="contact">
					 <a href="mailto:info@matthewstechnology.com">Contact us by clicking here.</a>
				</p>
			</div> <!-- id="footer" -->
		</div> <!-- id="wrapper" -->
	</body>
</html>
